services:
  api:
    build: .
    container_name: promethium_api
    ports:
      - "8080:8000"
    volumes:
      - .:/app
    command: python -m fastapi dev app/main.py --host 0.0.0.0 --port 8000
    environment:
      - PYTHONUNBUFFERED=1